#!/usr/bin/env sh

set -e

for SCRIPT in $(find -L ${BASH_SOURCE[0]}.d -type f | sort)
do
    echo " "
    echo "Executing ${SCRIPT}"
    if ! "${SCRIPT}"; then
        echo "Failed to execute ${SCRIPT}"
    fi
done
